[build]
  publish = "."
  functions = "netlify/functions"
  command = "npm install"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"
  included_files = ["node_modules/yahoo-finance2/**"]
