[build]
  publish = "."
  functions = "netlify/functions"
  command = "npm install"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "https://poppas-vertical-spread-screener.onrender.com/:splat"
  status = 302
  force = true
